title: "void"
baseurl: ""

date_format: "%Y-%m-%d"

highlighter: pygments

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

include: ["notes"]

production_url : http://username.github.com

permalink: /:title/

